ledger_cmd: /usr/bin/ledger
# Your accounts
ledger_file: /path/to/your/account.ledger

assets: Assets
expenses: Expenses
incomes: Incomes
legacy: Legacy funds

# For translations
locale: en

# Properly display values
decimals: 2
currency: $
decimal_sep: "."
thousand_sep: ","
currency_format: "%u%n"
date_format: "%m/%d/%Y"

# For HighCharts
value_prefix: ''
value_suffix: '$'
